### ISSUE TITLE
URL appends incorrectly if query param string already exists

### ISSUE THREAD

**Issue by pfriedman** [NUARIG/aker#19]
lib/form/mode.rb

```
  ##
  # Builds a Rack response that redirects to the login form.
  #
  # @return [Rack::Response]
  def on_ui_failure
    ::Rack::Response.new do |resp|
      target = login_url + '?url=' + escape(attempted_path)
      if env['aker.session_expired']
        target += '&session_expired=true'
      end
      resp.redirect(target)
    end
  end
```

builds a URL like this: 
/accounts/login?m_id=1?url=%some_path%3Fm_id%3D1
if the original request is some_path?m_id=1

**Comment by rsutphin** [comment]
I agree that it should not assume that the login URL doesn't have a QS. As a workaround, how about including :m_id in the route for the login page? (Assuming this is a rails app.) E.g.,

```
/accounts/:m_id/login
```

=>

```
/accounts/1/login
```

**Comment by hannahwhy** [comment]
So, when a user accesses `/resource?m=1`, they are currently redirected to `/login?m=1?url=/resource?m=1` (unescaped).  The original query string is preserved in the URL, so that should preserve the intended behavior (for GETs, anyway).

I think stripping out the query string in `login_url` (https://github.com/NUBIC/aker/blob/master/lib/aker/form/mode.rb#L80-83) should be enough to fix this.

**Comment by rsutphin** [comment]
> I think stripping out the query string in `login_url` should be enough to fix this.

But what if the login page actually needs the query parameters in order to work? That's how I understood the original request.

@pfriedman, what's the situation with your actual case? In `/accounts/login?m_id=1` is `m_id=1` necessary for proper functioning of the login page?

**Comment by hannahwhy** [comment]
> But what if the login page actually needs the query parameters in order to work? That's how I understood the original request.

That case came up when I was talking to @pfriedman.  In his case it was necessary that both the login page and the target resource have access to the query string, but that's since changed; and I wasn't able to come up with another case for having the login page have access to the query string.

I think (but am not sure) that it is okay to supply the query string to both actions, e.g. rewriting the login URL such that it becomes `/login?m=1&url=/resource?m=1`.  There could be problems if (say) a developer of a Rails application injects parameters out of `params` into a custom login page, but I think in that case it's safe to say that it is the responsibility of the developer to understand exactly what it is they're doing.

**Comment by rsutphin** [comment]
> I think (but am not sure) that it is okay to supply the query string to both actions, e.g. rewriting the login URL such that it becomes `/login?m=1&url=/resource?m=1`.

I think you'd need to escape the value of the `url` parameter, but otherwise I also think that this should be okay.

**Comment by rsutphin** [comment]
> In his case it was necessary that both the login page and the target resource have access to the query string, but that's since changed; and I wasn't able to come up with another case for having the login page have access to the query string.

Sorry, I breezed past this in my first read. My interpretation of the original issue was that the configured custom login URI was literally like this:

```
/accounts/login?m_id=1
```

When an unauthenticated request for `/resource` came in, I would expect the redirect to be to

```
/accounts/login?m_id=1&url=/resource
```

But that doesn't currently work because Aker assumes the login url doesn't have a QS already.

What I'm taking from @yipdw's last response is something different. That when the configured custom login url is

```
/accounts/login
```

and the user is accessing `/resource?m_id=1`, @pfriedman then wants the redirect to be to

```
/accounts/login?m_id=1&url=/resource?m_id=1
```

I.e., he's asking for the query parameters to be copied to the redirect to the login page. If I'm interpreting that correctly, I do not agree that Aker should do that. If the Aker-using application wants its login screen to be aware of some aspect of the URL from which the user was redirected, then the Aker-using application should look at the `url` parameter and parse its contents.

**Comment by rsutphin** [comment]
And now I see that that was in the original ticket all along:

> if the original request is some_path?m_id=1
