### ISSUE TITLE
Eliminate Aker::Rack::DefaultLogoutResponder

### ISSUE THREAD

**Issue by hannahwhy** [NUARIG/aker#4]
`Aker::Rack::DefaultLogoutResponder` doesn't seem necessary: in any real application using Aker's built-in modes, logout is handled by a mode-specific responder.  Eliminate the middleware.

**Comment by hannahwhy** [comment]
So, I just realized that `Aker::Form::CustomViewsMode` references `DefaultLogoutResponder`, if only in documentation.  Does this mean that the responder still has a reason to exist, or can we just say that using `CustomViewsMode` implies that you must write views for login and logout?

**Comment by rsutphin** [comment]
As you note, I modified `DefaultLogoutResponder` so that it would provide a default logout message in the event that a mode doesn't provide one (while not interfering if it does, even if it is provided below `DefaultLogoutResponder` in the stack). The only included mode that makes use of this is the `:custom_form` mode.

I don't have very strong opinions either way, but I think in general having defaults where a reasonable one can be defined is a good idea.

**Comment by hannahwhy** [comment]
After discussion, verdict is to keep `DefaultLogoutResponder`: since we do processing when `logout_path` is accessed, having the possibility of that processing terminate in a `404` seems weird.
